---
title: "Questions about FXTAS Sequence Data - Genetics"
output: 
  word_document:
    number_sections: true
---

```{r, include = FALSE}

knitr::opts_chunk$set(
  collapse = TRUE,
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  comment = "#>",
  fig.width = 7.5,
  fig.height = 4
)

```

```{r setup}
library(rSuStaIn)
library(pander)
library(table1)
library(dplyr)
library(magrittr)
NA.label1 = "Missing (see breakdown below)"
panderOptions("table.split.table", Inf)
# load_all()
```

```{r}

visit1 = 
  gp34 |> 
  arrange(`FXS ID`, `Visit Date`, `Event Name`) |> 
  group_by(`FXS ID`) |> 
  slice_head(n = 1) |>
  ungroup() |> 
  dplyr::rename(
    `Age at visit` = `Age at visit`
  ) |> 
  left_join(
    gp34 |> count(`FXS ID`, name = "# visits"),
    by = "FXS ID"
  ) |> 
  dplyr::mutate(`# visits` = factor(`# visits`, levels = 1:6))


```

```{r}
cgg.n = gp34 |> missing_pattern_by_ID(variable = "CGG")
```

# inconsistent CGG values

```{r, "multiple CGG values", include = TRUE, results = "asis"}

gp34 |> 
  semi_join(cgg.n |> dplyr::filter(n_vals > 1), by = "FXS ID") |> 
  dplyr::filter(!is.na(CGG)) |> 
  dplyr::select(`FXS ID`, `Visit Date`, `Event Name` , CGG) |> 
  arrange(`FXS ID`, `Visit Date`) |> 
  split(~`FXS ID`) |> 
  pander()

```

# Missing CGG values, compared with FXTAS Stage

```{r, results = "asis"}

visit1 |> 
  dplyr::filter(
    # is.na(ApoE) | 
    is.na(`CGG`) 
  ) |> 
  dplyr::select(`FXS ID`, `Event Name`, 
         # ApoE,
         CGG, 
         # `Floras Non-Sortable Allele Size (CGG) Results`,
         `FXTAS Stage (0-5)`) |> 
  # arrange(`FXTAS Stage (0-5)`) |> 
  pander()

```

