---
title: "potential-data-cleaning"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{potential-data-cleaning}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(rSuStaIn)
```

# Alcohol

Can we fill in some zeros in drinks per day using alcohol use/abuse?

```{r}

gp34 |> dplyr::filter(is.na(`# of drinks per day now`), `Alcohol use/abuse` %in% c("Past Only", "None"))

```

Maybe for GP3 only?

```{r}
gp34 |> dplyr::filter(
  Study == "GP3",
  is.na(`# of drinks per day now`), 
  `Alcohol use/abuse` %in% c("Past Only", "None"))

# no strange cases:
gp34 |> dplyr::filter(
  Study == "GP3",
  `# of drinks per day now` > 0, 
  `Alcohol use/abuse` %in% c("Past Only", "None"))
```

# Ataxia

```{r}

gp34 |> dplyr::select(Ataxia, `ataxia severity exam`) |> table(useNA ='ifany')

gp34 |> 
  dplyr::filter(`ataxia severity exam` == 0, !is.element(`ataxia exam`,"No"))

gp34 |> 
  dplyr::filter(Ataxia == "No", !is.element(`ataxia severity exam`, 0))

gp34 |> 
  dplyr::filter(!(Ataxia %in% "Yes"), `ataxia severity exam` %in% 1:4) |> 
  dplyr::select(`FXS ID`, `Event Name`, Ataxia, `ataxia severity exam`) |> 
  write.csv(file = "inst/extdata/fxtas/inconsistent_ataxia.csv")


```

