---
title: "timelines"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{timelines}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(rSuStaIn)
```


## plotly

```{r}

library(plotly)
library(dplyr)
gp34 |> 
  nest_by(Study) |> 
  dplyr::mutate(
    p = 
      plot_ly(data,
              type = "scatter",
              mode = "lines+markers",
              color = ~`FXS ID`,
              x = ~`Event Name`,
              y = ~`Age at visit`,
              showlegend = FALSE
      ) |> 
      plotly::layout(
        xaxis = list(title = "")
        # title = "banana"
      ) |> 
      list()
  ) |> 
  dplyr::pull(p) |> 
  plotly::subplot(
    nrows = 1, shareX = TRUE, shareY = TRUE)

```

## ggplot

```{r}

library(ggplot2)

plot1 = gp34 |> 
  ggplot(
    data = _,
    mapping = aes(
      color = `FXS ID`,
      group = `FXS ID`,
      y = `Event Name`,
      x = `Age at visit`
    )) +
  geom_point() + 
  geom_line() +
  theme_bw() +
  facet_grid(rows = vars(Gender)) +
  theme(legend.position="none")

print(plot1)

plot1 |> plotly::ggplotly()


```
